{% set version = "3.1" %}

package:
  name: django_polymorphic
  version: {{ version }}

source:
  url: https://github.com/django-polymorphic/django-polymorphic/archive/v{{ version }}.tar.gz
  sha256: 8afb7fe84051292093939e71ce4e5687a6064c69706fa86a622d05d115e9045c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - django >=2.1

test:
  imports:
    - polymorphic

about:
  home: https://github.com/chrisglass/django_polymorphic
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Seamless Polymorphic Inheritance for Django Models
  dev_url: https://github.com/django-polymorphic/django-polymorphic
  doc_url: https://django-polymorphic.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
