{% set version = "3.0.0" %}

package:
  name: django_polymorphic
  version: {{ version }}

source:
  url: https://github.com/django-polymorphic/django-polymorphic/archive/{{ version }}.tar.gz
  sha256: 98663022888ad812d00afd205d71b9f93a923173a9365d3363b60248a4ba01b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - django >=2.1

test:
  imports:
    - polymorphic

about:
  home: https://github.com/chrisglass/django_polymorphic
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Seamless Polymorphic Inheritance for Django Models
  dev_url: https://github.com/django-polymorphic/django-polymorphic
  doc_url: https://django-polymorphic.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
