travis:
  secure:
    BINSTAR_TOKEN: vMx8AXko660jgfazj1vqEedXWVX+VUlM3YRGJ2mawhEbPbNR5QOetKFeChwgNzR+j8R/Dcr/e4UMvX9pQkNR8P9caiF3WwjFWSuSQTO2wcAU/MCcKqivQWtVfmHQAF6ud/dyOuzsw08reoOaUNY7bBN0elbRJnh8Wl9uskKl8CUf8FI3JRe/JZRym5N7Z5exfFZXTyhiIEHEe+ADZHzvp2gF2qfG60t/+/qKNYWhQkRltnhPbWsZL7y9CGWWbxdSpqgN6soEeTIkE4/6Qf7s1/OBCaJIUfBPmXmZ8vpciwb0Xh+AwqWTSQ4C1a1Uwwny8HOfsoHVkNwaKu5pq2RQhFLSAZt6X9gXtVeGXRcJSX+A0M4uFLQR0UjDfX4kfLSxjZvrrueTOBwQwnhG1FuueD29B58o6WlLngsOIm7gRUN/va/Ddxbc6QvkicSKswuF2YAJm9govcqes26OtNGb8YsrdKIpwW++VBGZ3DdA2dOTUj9knKhZx4FVSbEbVqhpVygJYVNmls/JmLOOPNahJYQADJwRYrjt58NySFM6yRfLweTvTSlkItMbn70EUmqnU2nFs6ljPt0dYCGOr0qrrvHofe5fiusX9FNpjZlv1JA7+MfXiByTX/IsqckKJVelmpf11+nhEW1jhLGEI945eZgqqfY7NT5ueu2C899Gweg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
