travis:
  secure:
    BINSTAR_TOKEN: eOqUQCHissRk04zsWe097JzeTRZgV27VhrT+urWheSktY3WokxhwC+GdUXmKLWOlqhzhWNEfMvyDaPC3AbZbvf/UyfB3J4/fGfBGlIJa1qyvPhWQtCrWgIYfdA9tVN0L3anCqUetBgpi62CZEdFPfwwpeLOVB1D+Q48TAPkdKiuPcYPNCw6fpXEsyTuucbqxfocPNdHSqLgNgAF37PqSkJO/1qA/Ak/C5IEwmy9Ra/as86F0Xi5jzw82ITlkP1vcFroxmdbSYyJqPt4dxFJE+sHTLTdtk1mPaECNvWvl5hpXrzRv17eO3JaEo5gi9kz3rwer2Q2eeCWKu+nCjp58ZFiq56VPAU+yyJ7/MOCJ5FmlGdjrz1Ih50Asda/0sKsNIfSp2a3MH8AWxQJep4s+/amulO4RUhNnbTKr2I3w8iD5Q/H+yAy7JaBLjY34oDrFzXMZc3G+NcHx6PrnAbTLonZNw/nFOwYmDDQhNiKp8M5q1DPkeF0tfohUJB5Y4IC31Gpj5juoKs+I5GmTLAGvxhS21Tu75a3ME36SuoK/biJd1o3Q0Ls5fSymckPpEfpvzXumjtcLpXbR1xmqEsbY0jgThR3ypL9uOSiui6eCAy0jBt/EOCF24Ccm6qjLpeUlT6ximP21KaNVDxAAVfrELvvVJVUv3XpEIGWrCc6/33M=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
