travis:
  secure:
    BINSTAR_TOKEN: SJeVNKTLY1+jB7+UOQWYY7PXu2FwICxvV1VZctybYiDh0NyAu5J8Z0RcKASXpAwk5nIMhxsaq+EfJBt4Xfa01lGcKMUocZrgR4QrLouTaXGGyhopv7fQkg65c3OsEHTraBa28TwOLpA9AYf9+VJHjEmesB9dYFbDBmzF2k1KH4N49PQY9ndikGOltvJZvAa90y5lSh9AdSfhJ/GvJDNDZy/NAHLDXQBJmlAyy9SWoSvmd7uP6Iqg2aS3ZZrO7jE6+uLSYTKq+zt4lvpY97nLj0UVGPFl0TKJolvX9tKux5ZV6hYAAFI1mzCN7MukoUPocpF1qDA2zVUZcB/z1cTO38Z3sJGaUVemRJUDbWFnfM+50fFqF5zqEhHPLTZrKdebqY9+Bd3VBFSQnkUb59ApKG6waH+y8MzOBLMvl4RtGFYhrfDq7MaoXnFLG4sxjraU+EHLDfdovx8jxZj4Um5josx5ugQ/XY/0H4bJ02utgQx/PfaeLJVS47hee3NRte7hQ5isFKGs4n58zfYhDKTbHilhnCCUAxbir4jElE1cFerW+iiROMnpkJN6VnsOQR2A7udGnv3G3w7sKu3o2ynMiC7HlwZk3FTQ4xXY+UHn45TZA5JYWC8R6PRH5gxsXR06eDZ6molqso02ujHvhsXI3lr/ERW/nBIdr8k0tugUF28=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
